### ISSUE TITLE
Investigate: Better audio tagging support via mutagen library

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ZivaVatra/flac2all#18]
```
Investigate use of mutagen tagging library for better tag support (including 
embedded graphics) in flac2all

    * If good for our needs, to be implemented in v4
    * http://mutagen.readthedocs.org/en/latest/

```

Original issue reported on code.google.com by `i...@ziva-vatra.com` on 13 Jan 2015 at 4:22

**Comment by ZivaVatra** [comment]
Decided against this. Adding a third party library means we have to redo the tag logic, and we would have to handle a lot more of it (at the moment we can offload a fair bit to the encoders). 

Really not much benefit for the moment.
