### ISSUE TITLE
cannot work without opusenc

### ISSUE THREAD

**Issue by itscience** [ZivaVatra/flac2all#28]
Without installing opus-tools from my Arch Repository, flac2all will produce the following error

/bin/sh: line 0: type: opusenc: not found
sh: opusenc: command not found
Traceback (most recent call last):
  File "/usr/bin/flac2all", line 834, in <module>
    opusClass = opus()
  File "/usr/bin/flac2all", line 109, in __init__
    data = re.search("\d\.\d\.\d",data).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

I listed it as a problem on the forums and was told to let you know
https://bbs.archlinux.org/viewtopic.php?id=206993
Hope this was useful. It works once I install the package.
Thank you for your work, I enjoy using your script :+1:

**Comment by ZivaVatra** [comment]
Thanks for letting me know. The script should not bomb out unless you are actually trying to convert to opus. I will investigate.

**Comment by maxthomas** [comment]
Same error here.

Looks like a check for `== None then return None` on line 108 could solve the issue.

Either way, thanks for your work on this!

**Comment by ZivaVatra** [comment]
You're welcome, really glad you like it. Never thought I would still be working on this script 10 years later, but there you go :)

Fix pushed into the latest master branch. I ran my unit tests on it, but if you two can pull the latest version and test to make sure you don't see any other errors, I would appreciate it.  Please re-open this ticket if it still doesn't work for you.
