### ISSUE TITLE
Show filename on exception

### ISSUE THREAD

**Issue by avuton** [ZivaVatra/flac2all#30]
Not so much because there's an exception (these things happen, I don't care too much) but I would love to know which of the 400 files being converted was the target when the exception occurred on so I can evaluate the situation later.

The exception, for reference:
<code><pre>Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/scriptbin/flac2all.py", line 678, in encode_thread
    mp3Class.mp3convert(opts['lameopts'],current_file,outfile)
  File "/root/scriptbin/flac2all.py", line 577, in mp3convert
    encoder.write(line) #write it to the encoders buffer
IOError: [Errno 32] Broken pipe</pre></code>

**Comment by ZivaVatra** [comment]
This should be relatively simple to do, and as you say,  helpful.  v4 already has it, but v3 is lagging behind.

**Comment by ZivaVatra** [comment]
Latest master has the fix in place, give it a test and let me know if you find any problems. Thanks.

**Comment by avuton** [comment]
Will do, thank you so much for your time!
