### ISSUE TITLE
is the version of the latest release 2.79 or 3.79?

### ISSUE THREAD

**Issue by graysky2** [ZivaVatra/flac2all#37]
https://github.com/ZivaVatra/flac2all/tree/v3.79

**Comment by ZivaVatra** [comment]
It is 3.79.  Sorry about that, seems the script I use for automatically printing the revision isn't working, need to think of a new way of calculating revision numbers for tags.

**Comment by graysky2** [comment]
No problem.  I thought it was 2.79 based on the iterative nature of the previous tags.

**Comment by ZivaVatra** [comment]
Heya. Just a FYI. I pushed a new version. V4. This is in fact a rewrite, and with that, there is now a pip package for installation. 

Not sure how you want to package this in AUR, you got any preference?

**Comment by graysky2** [comment]
@ZivaVatra - I emailed you to your info@... address.  Let's the conversation there.
