### ISSUE TITLE
Skipping does not work if mode name does not equal file extension

### ISSUE THREAD

**Issue by mk190** [ZivaVatra/flac2all#38]
The check for existing file endings does not seem to work correctly in all cases. If I run the script with "vorbis" as an encoder mode, it does not skip existing files. Specifically, the line

`                if os.path.exists(outfile + "." + mode):`

seems to be the culprit, as it will look for "filename.vorbis" instead of "filename.ogg".

**Comment by ZivaVatra** [comment]
That does seem to be the problem. I've made an attempt at a fix on branch "version4.issue38". Feel free to checkout and test. I will test myself as well.

**Comment by mk190** [comment]
I've tested it and it seems to work properly for vorbis, so thank you for that fix.

**Comment by ZivaVatra** [comment]
You're welcome! Closing ticket.
