### ISSUE TITLE
Exception with opus conversion

### ISSUE THREAD

**Issue by giuseppeM99** [ZivaVatra/flac2all#39]
```
Exception in thread Thread 4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/flac2all_pkg/__init__.py", line 112, in run
    encoder = opus(opts['opusencopts'])
  File "/usr/lib/python2.7/site-packages/flac2all_pkg/opus.py", line 30, in __init__
    data = re.search("\d\.\d\.\d", data).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

opusenc version
```
opusenc opus-tools 0.2 (using libopus 1.3)
Copyright (C) 2008-2018 Xiph.Org Foundation
```

**Comment by ZivaVatra** [comment]
Hi, thanks for your report. Can you give me the distro name/version, as well as the version of flac2all you are using (it should say when you run with "-h").

**Comment by giuseppeM99** [comment]
I'm using Manjaro 18.0.4 Linux 5.0.5
flac2all version 4.1

**Comment by ZivaVatra** [comment]
Thanks, will try to replicate the bug, and update ticket as things progress

**Comment by ZivaVatra** [comment]
Ok, I think I have fixed the issue. On my Manjaro install the current "master" branch seems to convert to opus just fine. Please try it yourself and let me know if it works for you.

**Comment by giuseppeM99** [comment]
Can confirm, now it works well. Thanks.

**Comment by ZivaVatra** [comment]
Excellent! Thanks for the update. Closing ticket.
