### ISSUE TITLE
Add support for fdkaac

### ISSUE THREAD

**Issue by graysky2** [ZivaVatra/flac2all#40]
Easy for you to add support for [fdkaac](https://github.com/nu774/fdkaac)?

**Comment by ZivaVatra** [comment]
fdkaac is just a front end to libfdk_aac, which is the Fraunhofer aac implementation.

libfdk_aac is already supported via ffmpeg (https://trac.ffmpeg.org/wiki/Encode/AAC) assuming your ffmpeg is compiled with support built in. 

Version5 of flac2all adds ffmpeg support, and with it, all the codecs ffmpeg provides.

**Comment by graysky2** [comment]
Yea, I have used ffmpeg to do this (see below).  When are you expecting version 5?

```
#!/bin/bash
  
doit() {
  ffmpeg -i "${1}" -c:a libfdk_aac -vbr 5 -cutoff 20000 "${1%.*}".m4a
  touch -r "${1}" "${1%.*}.m4a"
}

export -f doit

find . -type f -name '*.flac' | perl-rename 'y/ /_/'
parallel doit ::: "$(find . -type f -name '*.flac')"
```

**Comment by ZivaVatra** [comment]
The deadline for Version5 is end of this year, to coincide with the deprecation of python2. 
Saying that, enough people have asked for python3 support (as a lot of distros have already switched to python3 as the default OS interpreter) that I am sure nobody will mind if it get released sooner :-)

Version5 works in my tests/daily use, but I would appreciate more testers, especially of the two new features (ffmpeg support and clustering). If you want to give it a try feel free to check out the "version5" branch and let me know if you spot any problems.

**Comment by ZivaVatra** [comment]
With the release of version5, this should now be supported via ffmpeg, please re-open ticket if you encounter any issues.
