### ISSUE TITLE
Add support for Musepack

### ISSUE THREAD

**Issue by averroista-latino** [ZivaVatra/flac2all#41]
https://wiki.hydrogenaud.io/index.php?title=Musepack

Musepack is still a competitive lossy codec. It would be great to add it to flac2all since there's no native support to transfer tags with the CLI command (mpcenc).

**Comment by ZivaVatra** [comment]
In theory it should be possible to do so. It just needs to have a module written for it, along with some musepack tagging library.

However I doubt I will do it myself, as I have no need for the codec and my time is limited.  FFmpeg supports decoding musepack, and if in future it supports encoding than flac2all will automatically support it then.

I will leave the ticket open for now in case someone shows interest in doing the dev work.

**Comment by ZivaVatra** [comment]
As it has been just over a year with no interest or activity on this ticket. I shall close it for now.
