### ISSUE TITLE
possible to specify output dir without codec name?

### ISSUE THREAD

**Issue by xdrie** [ZivaVatra/flac2all#50]
Hi, This is an excellent tool by the way:

I am running:
`flac2all opus -o outdir MusDir`

currently, it creates `outdir/opus` and puts all the files in there, with no way to change that subdirectory path or way to opt out. Would it be possible to have an option to suppress the automatic codec dir creation? so that the music would go straight to `outdir`. with multiple codecs they could all be mixed. obviously the current behavior should be the default, but i would like to have this as an option. thanks.

It seems like `nodirs` is supposed to do this, but the option doesn't look like it does anything. Was it perhaps overlooked?

**Comment by ZivaVatra** [comment]
From memory, there is a "-n" option, that does not create directories, and just dumps everything together. 

I've not used it in years, so give it a go and see if it works for you.

**Comment by xdrie** [comment]
> It seems like `nodirs` (`-n`) is supposed to do this, but the option doesn't look like it does anything. Was it perhaps overlooked?

**Comment by ZivaVatra** [comment]
It does seem to be broken, I've been going through the commit history to see when it broke, and from what I can see, it last worked in "version3" of flac2all, so about 5 years ago. 

Unfortunately flac2all has changed radically since then, so I will have to redo the logic more or less from scratch.

**Comment by ZivaVatra** [comment]
Initial work complete and tested. Seems ok. Can you please test? Branch is version5-nodirs. 

Let me know if it works for you, then I can merge into version5 for the next release.

**Comment by xdrie** [comment]
Hi, I tried it out, but it doesn't seem to do what I expected; this option completely removed all directory structure.

What I meant to request was an option to keep directory structure, but not create the separate `opus`, `ogg`, etc. dirs. Could we have an option to keep directory structure but not create the `opus` or `ogg` subdirectory?

**Comment by ZivaVatra** [comment]
Understood, so I have made some alterations to the logic, please pull the branch and try again. This time, "-n" takes an argument:

- "-n d" is for "no dir", this is the original logic, where everything gets put in the output directory with no paths at all.
- "-n m" is for "no modedir", this I believe is what you want. It will create the complete path, except the folder for the modes specified (test/mp3/vorbis/etc...)

Please test and let me know if it works for you.

**Comment by xdrie** [comment]
Excellent, I will give it a try soon and get back to you.

**Comment by ZivaVatra** [comment]
Any luck with trying it?

**Comment by xdrie** [comment]
Sorry, I am recovering from injury so I will not be able to try anything
for a few weeks.

- X

**Comment by ZivaVatra** [comment]
I understand, I hope your recovery is going well. I have tested the logic, and it works as I expect it to, even if it might not be exactly what you had in mind. As things stand, I have merged it into the version5 branch, and you can test it there. 

I will close this ticket now, please feel free to re-open if you need to.
