### ISSUE TITLE
Both master and version5 branch fail on Mac Catalina

### ISSUE THREAD

**Issue by sjthespian** [ZivaVatra/flac2all#54]
Neither the build from master or the origin/version5 branch will run on my Mac running Catalina 10.15.7. It looks like the code is using a python feature (_sem._semlock._get_value()) that isn't implemented on the Mac. The same command line works fine on a Linux system.

Here's the command I am using and the stacktrace.
```
> flac2all mp3 -n d -o DISC\ 1 DISC\ 1
UTC~00:31:49: Folder mp3 already exists, reusing...
UTC~00:31:50: We have 0 flac files to convert
Traceback (most recent call last):
  File "/usr/local/bin/flac2all", line 33, in <module>
    sys.exit(load_entry_point('flac2all==5.5', 'console_scripts', 'flac2all')())
  File "/usr/local/lib/python3.9/site-packages/flac2all_pkg/__init__.py", line 440, in main
    threaded_encode()
  File "/usr/local/lib/python3.9/site-packages/flac2all_pkg/multiprocess_encode.py", line 98, in encode
    log.info("We have %d non-flac files to copy across" % cQ.qsize())
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/queues.py", line 126, in qsize
    return self._maxsize - self._sem._semlock._get_value()
NotImplementedError
```

I found a workaround for a different package, but I didn't have time to dive in your queue code to see if it can be done here...
https://github.com/keras-team/autokeras/issues/368

**Comment by ZivaVatra** [comment]
Hello,

Thanks for raising the issue. flac2all is only tested/supported on Linux and FreeBSD, as those are the systems I use myself (and I have no versions of OSX to test on). So it is good to get feedback from Mac users.

Saying that, the newest versions of flac2all should not make use of the inbuilt Queue class anymore, as the underlying logic was moved to ZeroMQ. I will have a look and see what the issue might be.

**Comment by ZivaVatra** [comment]
Hello, 

Please try branch "issue-54" and let me know if the problem persists, thanks.

**Comment by fullstopslash** [comment]
I can confirm, I'm on big sur and was just having this issue, the issue-54 branch fixes it!

**Comment by ZivaVatra** [comment]
Excellent, many thanks for confirming! I now know flac2all works on Mac's as well :-) 

I will close this ticket and merge changes to master. Please re-open if problems persist.

**Comment by sjthespian** [comment]
I just pulled master and rebuilt and I'm still seeing the same failure on Catalina.

**Comment by ZivaVatra** [comment]
That is my mistake above. I merged to version5 branch, not master. Please try version5 and let me know if it works for you.

**Comment by sjthespian** [comment]
I just did a deeper cleanup (i.e. removing site-packages/flac2all_pkg/ by hand) and it's working from the version5 branch. Thanks for the quick fix!

**Comment by ZivaVatra** [comment]
Glad to hear it, thanks for the feedback. We are good to merge to master for next release now.
