### ISSUE TITLE
Overwrite if source file changes

### ISSUE THREAD

**Issue by amschuma** [ZivaVatra/flac2all#56]
This tool is great for making a smaller (more portable) mirror of my flac files! I recently fixed up a bunch of tags in some of my source files, which flac2all hasn't copied over to my ogg mirror. I was wondering if you could add an option to overwrite the outfile if source mtime is newer than outfile mtime in order to to detect changes?

**Comment by ZivaVatra** [comment]
Hi Amschuma,

That could be something that can be looked into, I will label it as a feature request. 

Thanks!

**Comment by amschuma** [comment]
Thanks so much!
